---
title: "About"
description: |
  Some things about myself  
output: 
  distill::distill_article:
    css: quang.css
---

Greetings!  

My name is Quang, and I am an aspiring biomedical data scientist from Vietnam currently living in the United States. I am currently a Ph.D. candidate in Quantitative Biomedical Sciences from Dartmouth College. I have broad interests in data science within the biopharmaceutical research sphere but I am most invested in using genomic technologies for public health purposes.        

### Education   

**Geisel School of Medicine at Dartmouth College** | Lebanon, NH  
Ph.D. Candidate in Quantitative Biomedical Sciences | September, 2017 - Expected June, 2022  

**Bates College** | Lewiston, ME  
B.S. in Biochemistry and Mathematics | September, 2013 - June, 2017 


### Recent Roles    

**Regeneron Pharmaceuticals** | Biostatistics Intern in early clinical development  
**The COVID Tracking Project at The Atlantic** | Data Quality and Science Communication  

### Skills and Interests  

* **R** for data related work: I am an `R` programmer for the past 5 years and use it in most of my projects. I mostly use `R` to perform statistical analysis (e.g. `glm`, `cmdstanr`, `lme4`) in the context of genomic (mostly microbiome) data sets (e.g. `phyloseq`, `dada2`, `DESeq2`). I am proficient in utilizing the `tidyverse` and `tidymodels` ecosystem, have experience developing R packages and Shiny dashboards, and can develop workflows using `targets`.    
* **Python** for backend analysis and workflow generation: I use `python` mostly for interacting with biological databases (NCBI, Pathway Tools via `biopython`), and writing reproducible workflows (using `snakemake`). I also use `python` for machine learning coursework and personal projects (`pytorch`, `tensorflow`, and `scikit-learn`).    
* **Julia and C++** for performance code: I am familiar with using `Julia` and `C++` for writing analyses or algorithms that require performance. This is done either for personal projects or integrated with `R` (via `Rcpp`).  
* **Shell/Bash scripting** for running command-line tools and utilities. 
* **Git/GitHub** for code versioning and continuous integration.  
* **SQL (SQLite and MySQL)** for creating and accessing data that cannot fit in memory.  
* **Slurm/Torque High Performance Computing** for analyses that require extra memory and computing time.  
* **Additional technologies I'm familiar with** include: `Rust`, `nextflow`  